#!/bin/sh -e

dir="$1"
shift

if [ -n "$dir" -a -d "$dir" ]; then
  cd "$dir"
fi

# XAUTHORITY file can change after a re-login or a restart, so search for the passed one
# by docker/podman exec in the mount point of its parent directory
if [ -n "$XAUTHORITY" -a -n "$XAUTHORITY_ORIG" -a ! -r "$XAUTHORITY" ]; then
  xauth_dir="`dirname "$XAUTHORITY_ORIG"`"
  xauth_file="`basename "$XAUTHORITY"`"
  XAUTHORITY="$xauth_dir/$xauth_file"
  if [ ! -r "$XAUTHORITY" ]; then
    XAUTHORITY="$XAUTHORITY_ORIG"
  fi
  export XAUTHORITY
fi

exec "$@"
