#!/bin/bash

set -e

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <full command to run as single argument like passed to '/bin/bash -c'>"
  exit 1
fi

if [ "$(id -u)" -eq 0 -a -n "$YBOX_HOST_UID" ] && getent passwd $YBOX_HOST_UID > /dev/null; then
  sudo -u "#$YBOX_HOST_UID" -g "#$YBOX_HOST_GID" /bin/bash -c "$1"
  status=$?
  if [ $status -ne 0 ]; then
    echo "FAILED (exit code = $status) in sudo execution of: $1"
    exit $status
  fi
else
  eval "$1"
  status=$?
  if [ $status -ne 0 ]; then
    echo "FAILED (exit code = $status) in execution of: $1"
    exit $status
  fi
fi
