# Configuration specific to each distribution (INI style file)

# Base configuration for the distribution
[base]
# name is required
name = CachyOS (amd64v3 image)
# Comma separated files to include before applying these settings.
# Paths can be absolute or relative to the location of this file.
includes = ../arch/distro.ini
# docker image of the distribution
image = docker.io/cachyos/cachyos-v3
# distribution scripts that need to be copied to the container in $YBOX_TARGET_SCRIPTS_DIR
# (should include init.sh, init-base.sh and init-user.sh scripts that are are normally required
# for all distributions)
scripts = ../arch/init-base.sh,../arch/init.sh,../arch/init-user.sh,../arch/pkgdeps.py,
          ../arch/list_fmt_long.py,../arch/add-gpg-key.sh
