#!/usr/bin/python3

from zbox.util import *


def main() -> int:
    args = parse_args()
    docker_cmd = get_docker_command(args, "-d")
    container_name = args.container_name

    if not check_running_zbox(docker_cmd, container_name, include_all=True):
        print_color(f"No zbox container named '{container_name}' found", fg=fgcolor.red)
        return 1

    if args.follow:
        log_result = subprocess.run([docker_cmd, "container", "logs", "-f", container_name])
    else:
        log_result = subprocess.run([docker_cmd, "container", "logs", container_name])
    if log_result.returncode != 0:
        print_color(f"FAILED to show logs of '{container_name}'", fg=fgcolor.red)
        return 1

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Show logs from a running or stopped zbox container")
    parser.add_argument("-d", "--docker-path", type=str,
                        help="path of docker/podman if not in /usr/bin")
    parser.add_argument("-f", "--follow", action="store_true",
                        help="follow log output like 'tail -f'")
    parser.add_argument("container_name", type=str, help="name of the running box")
    return parser.parse_args()


sys.exit(main())
