#!/usr/bin/python3

import argparse
import sys

from zbox.print import print_info
from zbox.util import get_docker_command, run_command, verify_zbox_state


def main(argv: list[str]) -> None:
    args = parse_args(argv)
    docker_cmd = get_docker_command(args, "-d")
    container_name = args.container_name

    verify_zbox_state(docker_cmd, container_name, expected_states=[])

    docker_args = [docker_cmd, "container", "logs"]
    if args.follow:
        docker_args.append("-f")
    docker_args.append(container_name)
    try:
        run_command(docker_args, error_msg=f"showing logs '{container_name}'")
    except KeyboardInterrupt:
        # allow for user interruption during follow or otherwise for a large log
        print()
        print_info("Interrupt")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Show logs from a running or stopped zbox container")
    parser.add_argument("-d", "--docker-path", type=str,
                        help="path of docker/podman if not in /usr/bin")
    parser.add_argument("-f", "--follow", action="store_true",
                        help="follow log output like 'tail -f'")
    parser.add_argument("container_name", type=str, help="name of the running zbox")
    return parser.parse_args(argv)


if __name__ == "__main__":
    main(sys.argv[1:])
