#!/usr/bin/python3

import sys

from zbox.util import *


def main() -> int:
    args = parse_args()
    docker_cmd = get_docker_command(args, "-d")
    container_name = args.container_name

    if not check_zbox_state(docker_cmd, container_name, ["running"]):
        print_error(f"No active zbox container named '{container_name}' found")
        return 1

    run_result = subprocess.run([docker_cmd, "exec", "-it", container_name, args.shell])
    if run_result.returncode != 0:
        print_error(f"FAILURE in {args.shell} execution on '{container_name}'")
        return 1

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Open a shell on a running zbox container")
    parser.add_argument("-d", "--docker-path", type=str,
                        help="path of docker/podman if not in /usr/bin")
    parser.add_argument("-s", "--shell", type=str, default="/bin/bash",
                        help="run the given shell (default is /bin/bash)")
    parser.add_argument("container_name", type=str, help="name of the running zbox")
    return parser.parse_args()


sys.exit(main())
