#!/usr/bin/python3

import argparse

from zbox.util import fgcolor, get_docker_command, run_command, print_color, verify_zbox_state


def main() -> None:
    args = parse_args()
    docker_cmd = get_docker_command(args, "-d")
    container_name = args.container_name

    verify_zbox_state(docker_cmd, container_name, ["exited", "stopped"], error_msg=" stopped ")

    print_color(f"Restarting zbox container '{container_name}'", fg=fgcolor.cyan)
    run_command([docker_cmd, "container", "start", container_name], error_msg="container start")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Restart a stopped zbox container")
    parser.add_argument("-d", "--docker-path", type=str,
                        help="path of docker/podman if not in /usr/bin")
    parser.add_argument("container_name", type=str, help="name of the stopped zbox")
    return parser.parse_args()


main()
