#!/usr/bin/python3

import sys

from zbox.util import *


def main() -> int:
    args = parse_args()
    docker_cmd = get_docker_command(args, "-d")
    container_name = args.container_name

    if not check_zbox_state(docker_cmd, container_name, expected_states=[]):
        print_error(f"No zbox container named '{container_name}' found")
        return 1

    if args.follow:
        try:
            log_result = subprocess.run([docker_cmd, "container", "logs", "-f", container_name])
            exit_code = log_result.returncode
        except KeyboardInterrupt:
            exit_code = 0  # pretend everything is fine
            pass
    else:
        log_result = subprocess.run([docker_cmd, "container", "logs", container_name])
        exit_code = log_result.returncode
    if exit_code != 0:
        print_error(f"FAILED to show logs of '{container_name}'")
        return 1

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Show logs from a running or stopped zbox container")
    parser.add_argument("-d", "--docker-path", type=str,
                        help="path of docker/podman if not in /usr/bin")
    parser.add_argument("-f", "--follow", action="store_true",
                        help="follow log output like 'tail -f'")
    parser.add_argument("container_name", type=str, help="name of the running zbox")
    return parser.parse_args()


sys.exit(main())
