#!/usr/bin/python3

from zbox.util import *


def main() -> int:
    args = parse_args()
    docker_cmd = get_docker_command(args, "-d")

    docker_args = [docker_cmd, "container", "ls"]
    if args.all:
        docker_args.append("--all")
        docker_args.append(f"--filter=label={ZboxLabel.CONTAINER_TYPE}")
    else:
        docker_args.append(f"--filter=label={ZboxLabel.CONTAINER_PRIMARY}")
    if args.long_format:
        docker_args.append("--no-trunc")
    log_result = subprocess.run(docker_args)
    if log_result.returncode != 0:
        print_color("FAILED to list zbox containers", fg=fgcolor.red)
        return 1

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="List zbox containers")
    parser.add_argument("-a", "--all", action="store_true",
                        help="""Show all containers including stopped and temporary ones.
                                Default is to show only running zbox containers and also skip
                                any temporary containers spun by zbox-create.""")
    parser.add_argument("-d", "--docker-path", type=str,
                        help="path of docker/podman if not in /usr/bin")
    parser.add_argument("-l", "--long-format", action="store_true",
                        help="display extended information and without truncating fields")
    return parser.parse_args()


sys.exit(main())
